# Generated by Django 4.2.5 on 2023-10-02 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0012_alter_cliente_fecha_nacimiento_and_more'),
        ('Cuidado', '0002_alter_ficha_veterinario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Usuario.cliente'),
        ),
    ]
