# Generated by Django 4.2.5 on 2023-11-15 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0012_alter_cliente_fecha_nacimiento_and_more'),
        ('Cuidado', '0005_ficha_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.cliente'),
        ),
    ]
