# Generated by Django 4.2.5 on 2023-09-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='role_id',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rol',
            field=models.CharField(choices=[('Recepcionista', 'Recepcionista'), ('Administrador', 'Administrador'), ('Veterinario', 'Veterinario')], max_length=50),
        ),
    ]
