# Generated by Django 4.2.5 on 2023-09-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_empleado_role_id_alter_empleado_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='role_id',
            field=models.IntegerField(unique=True),
        ),
    ]
