# Generated by Django 4.2.5 on 2023-09-20 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_alter_empleado_role_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='role_id',
        ),
    ]
