# Generated by Django 4.2.5 on 2023-09-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0006_alter_cliente_user_alter_empleado_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rut',
            field=models.CharField(default='RUT', max_length=12),
        ),
        migrations.AddField(
            model_name='cliente',
            name='second_last_name',
            field=models.CharField(default='Segundo Apellido', max_length=150),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='numero_telefono',
            field=models.CharField(default='Teléfono', max_length=15),
        ),
        migrations.AddField(
            model_name='empleado',
            name='rut',
            field=models.CharField(default='RUT', max_length=12),
        ),
        migrations.AddField(
            model_name='empleado',
            name='second_last_name',
            field=models.CharField(default='Segundo Apellido', max_length=150),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_telefono',
            field=models.CharField(default='Teléfono', max_length=15),
        ),
    ]
