# Generated by Django 4.2.5 on 2023-09-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0007_cliente_rut_cliente_second_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_telefono',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='second_last_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(default='1'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='numero_telefono',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rut',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='second_last_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
