# Generated by Django 4.2.5 on 2023-09-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0010_alter_cliente_rut_alter_empleado_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rut',
            field=models.CharField(default='', max_length=12),
        ),
    ]
