# Generated by Django 4.2.5 on 2023-10-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaccion', '0003_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
