# Generated by Django 4.2.5 on 2023-10-31 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaccion', '0006_ordendecompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='carrito',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
