# Generated by Django 4.2.5 on 2023-10-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaccion', '0007_carrito_carrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
