# Generated by Django 4.2.5 on 2023-11-04 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Transaccion', '0008_contenidocarrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordendecompra',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='ordendecompra',
            name='object_id',
        ),
        migrations.AddField(
            model_name='ordendecompra',
            name='codigo_transaccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordendecompra',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transaccion.ordendecompra')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Transaccion.producto')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Transaccion.servicio')),
            ],
        ),
        migrations.AddField(
            model_name='ordendecompra',
            name='productos',
            field=models.ManyToManyField(through='Transaccion.DetalleOrden', to='Transaccion.producto'),
        ),
        migrations.AddField(
            model_name='ordendecompra',
            name='servicios',
            field=models.ManyToManyField(through='Transaccion.DetalleOrden', to='Transaccion.servicio'),
        ),
    ]
