# Generated by Django 4.2.5 on 2023-11-04 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transaccion', '0009_remove_ordendecompra_cantidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordendecompra',
            old_name='codigo_transaccion',
            new_name='token_ws',
        ),
    ]
