# Generated by Django 4.2.5 on 2023-11-05 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaccion', '0010_rename_codigo_transaccion_ordendecompra_token_ws'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendecompra',
            name='estado',
            field=models.CharField(choices=[('INITIALIZED', 'Inicializada'), ('AUTHORIZED', 'Autorizada'), ('REVERSED', 'Reversada'), ('FAILED', 'Fallida'), ('NULLIFIED', 'Anulada'), ('PARTIALLY_NULLIFIED', 'Parcialmente Anulada'), ('CAPTURED', 'Capturada'), ('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=64),
        ),
    ]
