# Generated by Django 4.2.5 on 2023-11-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaccion', '0012_alter_ordendecompra_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendecompra',
            name='buy_order',
            field=models.CharField(blank=True, max_length=26, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ordendecompra',
            name='session_id',
            field=models.CharField(blank=True, max_length=61, null=True),
        ),
    ]
