# Generated by Django 4.2.5 on 2023-11-05 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transaccion', '0013_ordendecompra_buy_order_ordendecompra_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordendecompra',
            name='buy_order',
        ),
        migrations.RemoveField(
            model_name='ordendecompra',
            name='session_id',
        ),
    ]
