# Generated by Django 4.2.5 on 2023-11-06 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0012_alter_cliente_fecha_nacimiento_and_more'),
        ('Transaccion', '0014_remove_ordendecompra_buy_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('total', models.PositiveIntegerField(default=0)),
                ('pago_cliente', models.PositiveIntegerField(default=0)),
                ('cambio', models.PositiveIntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrdenVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('subtotal', models.PositiveIntegerField(default=0)),
                ('orden_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transaccion.ordenventa')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Transaccion.producto')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Transaccion.servicio')),
            ],
        ),
    ]
