# Generated by Django 4.2.5 on 2023-11-06 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0012_alter_cliente_fecha_nacimiento_and_more'),
        ('Transaccion', '0015_ordenventa_detalleordenventa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdenVenta',
            new_name='OrdenDeVenta',
        ),
    ]
