# Generated by Django 4.2.5 on 2023-11-08 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Transaccion', '0016_rename_ordenventa_ordendeventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleordenventa',
            name='orden_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalleordenventa_set', to='Transaccion.ordendeventa'),
        ),
    ]
