# Generated by Django 4.2.5 on 2023-11-14 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0012_alter_cliente_fecha_nacimiento_and_more'),
        ('Transaccion', '0017_alter_detalleordenventa_orden_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.cliente'),
        ),
        migrations.AlterField(
            model_name='ordendecompra',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.cliente'),
        ),
    ]
