# Generated by Django 4.2.5 on 2023-11-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaccion', '0018_alter_carrito_cliente_alter_ordendecompra_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendecompra',
            name='monto_cuotas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ordendecompra',
            name='numero_cuotas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordendecompra',
            name='tipo_pago',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
