# Generated by Django 4.2.5 on 2023-11-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaccion', '0020_ordendecompra_numero_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='reembolso_solicitado',
            field=models.BooleanField(default=False, verbose_name='¿Ha solicitado reembolso?'),
        ),
        migrations.AddField(
            model_name='detalleordenventa',
            name='reembolso_solicitado',
            field=models.BooleanField(default=False, verbose_name='¿Ha solicitado reembolso?'),
        ),
    ]
