# Generated by Django 4.2.5 on 2023-11-16 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transaccion', '0021_detalleorden_reembolso_solicitado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleorden',
            name='reembolso_solicitado',
        ),
        migrations.RemoveField(
            model_name='detalleordenventa',
            name='reembolso_solicitado',
        ),
    ]
