# Generated by Django 4.2.5 on 2023-09-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(max_length=100)),
                ('cantidad_pagada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('cantidad_vendida', models.PositiveIntegerField()),
                ('total_ingresos', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
