# Generated by Django 4.2.5 on 2023-09-20 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cita', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='Mascota',
            new_name='mascota',
        ),
    ]
