# Generated by Django 4.2.5 on 2023-09-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cita', '0003_remove_mascota_historial_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='especie',
            field=models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(choices=[('Akita Inu', 'Akita Inu'), ('Alaskan Malamute', 'Alaskan Malamute'), ('Barzoi', 'Barzoi'), ('Basset Azul de Gascuña', 'Basset Azul de Gascuña'), ('Basset Hound', 'Basset Hound'), ('Beagle', 'Beagle'), ('Beagle Harrier', 'Beagle Harrier'), ('Beauceron', 'Beauceron'), ('Bichón Maltés', 'Bichón Maltés'), ('Bobtail', 'Bobtail'), ('Border Collie', 'Border Collie'), ('Boxer', 'Boxer'), ('Boyero de Berna', 'Boyero de Berna'), ('Braco Alemán', 'Braco Alemán'), ('Braco Francés', 'Braco Francés'), ('Briard', 'Briard'), ('Bull terrier Inglés', 'Bull terrier Inglés'), ('Bulldog Francés', 'Bulldog Francés'), ('Bulldog Inglés', 'Bulldog Inglés'), ('Bullmastiff', 'Bullmastiff'), ('Cairn Terrier', 'Cairn Terrier'), ('Cane Corso', 'Cane Corso'), ('Caniche', 'Caniche'), ('Cavalier King Charles', 'Cavalier King Charles'), ('Chihuahua', 'Chihuahua'), ('Chow Chow', 'Chow Chow'), ('Cocker Spaniel Americano', 'Cocker Spaniel Americano'), ('Cocker Spaniel Inglés', 'Cocker Spaniel Inglés'), ('Collie Rough', 'Collie Rough'), ('Collie Smooth', 'Collie Smooth'), ('Dálmata', 'Dálmata'), ('Doberman', 'Doberman'), ('Dogo Argentino', 'Dogo Argentino'), ('Dogo de Burdeos', 'Dogo de Burdeos'), ('Epagneul Bretón', 'Epagneul Bretón'), ('Epagneul Francés', 'Epagneul Francés'), ('Epagneul Japonés', 'Epagneul Japonés'), ('Fox Terrier', 'Fox Terrier'), ('Galgo Español', 'Galgo Español'), ('Galgo Irlandés', 'Galgo Irlandés'), ('Golden Retriever', 'Golden Retriever'), ('Gordon Setter', 'Gordon Setter'), ("Gos d'Atura", "Gos d'Atura"), ('Gran Danés', 'Gran Danés'), ('Husky Siberiano', 'Husky Siberiano'), ('Komondor', 'Komondor'), ('Labrador Retriever', 'Labrador Retriever'), ('Lebrel Afgano', 'Lebrel Afgano'), ('Lebrel Polaco', 'Lebrel Polaco'), ('Mastiff', 'Mastiff'), ('Mastín de los Pirineos', 'Mastín de los Pirineos'), ('Mastín Español', 'Mastín Español'), ('Mastín Napolitano', 'Mastín Napolitano'), ('Montaña de los Pirineos', 'Montaña de los Pirineos'), ('Norfolk Terrier', 'Norfolk Terrier'), ('Norwich Terrier', 'Norwich Terrier'), ('Papillon', 'Papillon'), ('Pastor Alemán', 'Pastor Alemán'), ('Pastor Australiano', 'Pastor Australiano'), ('Pastor Belga', 'Pastor Belga'), ('Pastor Blanco Suizo', 'Pastor Blanco Suizo'), ('Pastor de los Pirineos', 'Pastor de los Pirineos'), ('Pekinés', 'Pekinés'), ('Pequeño Azul de Gascuña', 'Pequeño Azul de Gascuña'), ('Pequeño Basset Griffon', 'Pequeño Basset Griffon'), ('Pequeño Brabantino', 'Pequeño Brabantino'), ('Pequeño Perro León', 'Pequeño Perro León'), ('Pequeño Perro Ruso', 'Pequeño Perro Ruso'), ('Pequeño Sabueso Suizo', 'Pequeño Sabueso Suizo'), ('Perdiguero de Burgos', 'Perdiguero de Burgos'), ('Perdiguero Portugués', 'Perdiguero Portugués'), ('Perro de Agua Español', 'Perro de Agua Español'), ('Perro Lobo de Checoslovaquia', 'Perro Lobo de Checoslovaquia'), ('Pinscher miniatura', 'Pinscher miniatura'), ('Pit Bull', 'Pit Bull'), ('Podenco Canario', 'Podenco Canario'), ('Podenco Ibicenco', 'Podenco Ibicenco'), ('Pointer Inglés', 'Pointer Inglés'), ('Presa Canario', 'Presa Canario'), ('Pug', 'Pug'), ('Rafeiro do Alentejo', 'Rafeiro do Alentejo'), ('Rottweiler', 'Rottweiler'), ('Samoyedo', 'Samoyedo'), ('San Bernardo', 'San Bernardo'), ('Schnauzer gigante', 'Schnauzer gigante'), ('Schnauzer mediano', 'Schnauzer mediano'), ('Schnauzer miniatura', 'Schnauzer miniatura'), ('Scottish Terrier', 'Scottish Terrier'), ('Setter Inglés', 'Setter Inglés'), ('Setter Irlandés', 'Setter Irlandés'), ('Shar Pei', 'Shar Pei'), ('Shih Tzu', 'Shih Tzu'), ('Spitz', 'Spitz'), ('Springer Spaniel Galés', 'Springer Spaniel Galés'), ('Springer Spaniel Inglés', 'Springer Spaniel Inglés'), ('Teckel', 'Teckel'), ('Terranova', 'Terranova'), ('Weimaraner', 'Weimaraner'), ('Westies', 'Westies'), ('Whippet', 'Whippet'), ('Yorkshire Terrier', 'Yorkshire Terrier')], max_length=50),
        ),
    ]
