# Generated by Django 4.2.5 on 2023-09-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cita', '0005_alter_mascota_raza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(blank=True, choices=[], max_length=50),
        ),
    ]
