# Generated by Django 4.2.5 on 2023-09-28 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cita', '0010_alter_cita_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='mascota',
            field=models.ForeignKey(limit_choices_to={'cliente': models.F('cliente')}, on_delete=django.db.models.deletion.CASCADE, to='Cita.mascota'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(max_length=50),
        ),
    ]
