# Generated by Django 4.2.5 on 2023-09-29 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cita', '0011_alter_cita_mascota_alter_mascota_raza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cita.mascota'),
        ),
    ]
