# Generated by Django 4.2.5 on 2023-09-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cita', '0014_alter_mascota_raza'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='estado',
            field=models.CharField(choices=[('ConSuDueño', 'Con su dueño'), ('EnGuarderia', 'En Guardería'), ('SiendoAtendida', 'Siendo atendida'), ('EnCirugia', 'En cirugía'), ('EnCuidado', 'En cuidado post atención'), ('DadaDeAlta', 'Data de alta'), ('Fallecida', 'Fallecida')], default='ConSuDueño', max_length=50),
        ),
    ]
