# Generated by Django 4.2.5 on 2023-09-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cita', '0016_alter_mascota_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='estado',
            field=models.CharField(choices=[('Con su dueño', 'Con su dueño'), ('En Guardería', 'En Guardería'), ('Siendo atendida', 'Siendo atendida'), ('En cirugía', 'En cirugía'), ('En cuidado post atención', 'En cuidado post atención'), ('Data de alta', 'Data de alta'), ('Fallecida', 'Fallecida')], default='Con Su Dueño', max_length=50),
        ),
    ]
