# Generated by Django 4.2.5 on 2023-11-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cita', '0020_alter_mascota_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='ha_pagado',
            field=models.BooleanField(default=False, verbose_name='¿Ha pagado?'),
        ),
    ]
